apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-b
spec:
    replicas: 3
    selector:
        matchLabels:
            app: service-b
    template:
        metadata:
            name: service-b
            labels:
                app: service-b
        spec:
            containers:
            - name: service-b
              image: gcr.io/k8s-fb/k8s-fb/app:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "service-b"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                requests: 
                    cpu: 140m
                    memory: 24Mi
                limits:
                    cpu: 1000m
                    memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
    name: service-b-svc
spec:
    type: LoadBalancer
    selector:
        app: service-b
    ports:
    - name: metrics
      port: 80
      nodePort: 31051
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: service-b-autoscaler
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: service-b
    minReplicas: 3
    maxReplicas: 50
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
