apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-c
spec:
    replicas: 3
    selector:
        matchLabels:
            app: service-c
    template:
        metadata:
            name: service-c
            labels:
                app: service-c
        spec:
            containers:
            - name: service-c
              image: gcr.io/k8s-fb/k8s-fb/app:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "service-c"
              - name: DEPENDENCIES
                value: '{"destinations":[{"target":"http://service-d-svc.default.svc.cluster.local/load","request_payload_kb_size":50,"config":{"memory_params":{"duration_seconds":0.2,"kb_count":50},"cpu_params":{"duration_seconds":0.2,"load":0.2}}}]}'
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                requests: 
                    cpu: 140m
                    memory: 24Mi
                limits:
                    cpu: 1000m
                    memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
    name: service-c-svc
    labels:
      app: service-c
spec:
    type: LoadBalancer
    selector:
        app: service-c
    ports:
    - name: metrics
      port: 80
      nodePort: 31052
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: service-c-autoscaler
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: service-c
    minReplicas: 3
    maxReplicas: 50
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
