apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-b
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: service-b